a, b, i, j, x, y = input().split()
a = float (a)
b = float (b)
i = float (i)
j = float (j)
x = float (x)
y = float (y)
hasil = (a-b)*(i/j)-(x+y)
print("%.3f\n" %hasil)

a1, b1 = input().split()
i1, j1 = input().split()
x1, y1 = input().split()
a1 = float (a1)
b1 = float (b1)
i1 = float (i1)
j1 = float (j1)
x1 = float (x1)
y1 = float (y1)
hasil1 = (a1-b1)*(i1/j1)-(x1+y1)
print("%.3f\n" %hasil1)